-- ⚡ Enargy: PostgreSQL Schema Initialization

-- 1. Table: energy_readings
-- Stores incoming IoT data from ESP32 and associates it with blockchain hashes.
CREATE TABLE IF NOT EXISTS energy_readings (
    id SERIAL PRIMARY KEY,
    meter_id VARCHAR(50) NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    voltage NUMERIC(10, 2),
    current NUMERIC(10, 3),
    power NUMERIC(10, 2),
    energy_kwh NUMERIC(15, 4),
    hash TEXT,                         -- Local data hash generated by ESP32
    blockchain_tx_hash TEXT            -- Transaction hash after anchoring to Ethereum
);

-- 2. Table: payments
-- Handles billing status and Razorpay payment details.
CREATE TABLE IF NOT EXISTS payments (
    id SERIAL PRIMARY KEY,
    meter_id VARCHAR(50) NOT NULL,
    bill_month VARCHAR(20) NOT NULL,   -- e.g., "April 2026"
    amount NUMERIC(10, 2) NOT NULL,
    razorpay_order_id VARCHAR(100),
    razorpay_payment_id VARCHAR(100),
    status VARCHAR(20) DEFAULT 'pending', -- pending, paid, failed
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexing for performance
CREATE INDEX IF NOT EXISTS idx_meter_id ON energy_readings(meter_id);
CREATE INDEX IF NOT EXISTS idx_payment_meter ON payments(meter_id);
